version: '3.3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.4.14
    hostname: zookeeper
    ports:
      - "2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka0:
    image: wurstmeister/kafka:2.12-2.4.1
    depends_on:
      - zookeeper
    hostname: kafka0
    ports:
      - "33092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:33092,INTERNAL://kafka0:9093"
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  kafka1:
    image: wurstmeister/kafka:2.12-2.4.1
    depends_on:
      - zookeeper
    hostname: kafka1
    ports:
      - "34092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:34092,INTERNAL://kafka1:9093"
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  kafka2:
    image: wurstmeister/kafka:2.12-2.4.1
    depends_on:
      - zookeeper
    hostname: kafka2
    ports:
      - "35092:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:35092,INTERNAL://kafka2:9093"
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  postgres:
    image: postgres:12
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
      POSTGRES_DB: appdb
